### ISSUE TITLE
Loose Connection

### ISSUE THREAD

**Issue by codingsound** [cgwennap/pyHitBot#1]
in your code the bot looses connection, it gets a on_close and exits

**Comment by cgwennap** [comment]
Can you be more specific about what causes the connection to be lost?

**Comment by codingsound** [comment]
thats a problem to be more specific, because the bot looses connection after a few seconds, there isnt coming any message why, just closes the connection

**Comment by cgwennap** [comment]
Hmm. Can you provide your system information and the output log when you run testsocket.py?

**Comment by codingsound** [comment]
Sorry, it was my mistake. I had sending "2::" when receiving "2::" with a wrong intent so it didnt answer "2::".
Your Code is working well
sorry

**Comment by cgwennap** [comment]
Ok, I've never had a problem with the "2::" ping response, but that's apparently what happens if the ping response gets sent incorrectly. Thanks for the information, marking this as closed.
